In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [2]:
obj = pd.Series([4, 7, 3, 4,])

In [3]:
obj

0    4
1    7
2    3
3    4
dtype: int64

In [4]:
obj.values

array([4, 7, 3, 4], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4, 7, -5, 3], index=['a', 'b', 'c', 'd'])

In [7]:
obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [8]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [9]:
obj2['a']

4

In [10]:
obj2['d'] # 借助索引来访问值 类似于字典

3

In [11]:
obj2[['a', 'b', 'd']] # numpy中的神奇索引类似

a    4
b    7
d    3
dtype: int64

In [12]:
obj2[obj2 > 0] # numpy中的访问方式

a    4
b    7
d    3
dtype: int64

In [13]:
obj2 * 2

a     8
b    14
c   -10
d     6
dtype: int64

In [14]:
np.exp(obj2) # numpy可以直接操作Series

a      54.598150
b    1096.633158
c       0.006738
d      20.085537
dtype: float64

In [15]:
np.sum(obj2)

9

In [16]:
np.mean(obj2, axis=0)

2.25

In [17]:
'b' in obj2

True

In [18]:
'fuck' in obj2

False

In [19]:
sdata = {'Ohio': 3500, "Texas": 7100, "Oregon": 1600, 'Utanh':500}

In [20]:
obj3 = pd.Series(sdata)

In [21]:
obj3

Ohio      3500
Texas     7100
Oregon    1600
Utanh      500
dtype: int64

In [22]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [23]:
obj4 = pd.Series(sdata, index=states)

In [24]:
obj4

California       NaN
Ohio          3500.0
Oregon        1600.0
Texas         7100.0
dtype: float64

In [25]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [27]:
obj4[obj4.isnull()] # 使用布尔索引 访问缺失值

California   NaN
dtype: float64

In [28]:
obj4[obj4.notnull()]

Ohio      3500.0
Oregon    1600.0
Texas     7100.0
dtype: float64

In [29]:
# Series自动对齐
obj3

Ohio      3500
Texas     7100
Oregon    1600
Utanh      500
dtype: int64

In [30]:






obj4

California       NaN
Ohio          3500.0
Oregon        1600.0
Texas         7100.0
dtype: float64

In [31]:
obj3 + obj4

California        NaN
Ohio           7000.0
Oregon         3200.0
Texas         14200.0
Utanh             NaN
dtype: float64

In [32]:


obj4.name = 'population';obj4.index.name = 'state'

In [33]:

obj4

state
California       NaN
Ohio          3500.0
Oregon        1600.0
Texas         7100.0
Name: population, dtype: float64

In [34]:
obj

0    4
1    7
2    3
3    4
dtype: int64

In [35]:
obj.index = ['a', 'b', 'c', 'd']

In [36]:
obj.index.name = 'alpha'

In [37]:
obj

alpha
a    4
b    7
c    3
d    4
dtype: int64

In [38]:
obj.values

array([4, 7, 3, 4], dtype=int64)

In [39]:
type(obj.values)

numpy.ndarray

In [40]:
obj.index

Index(['a', 'b', 'c', 'd'], dtype='object', name='alpha')

In [41]:
display(np.sum(obj.values))
display('hello')

18

'hello'

In [42]:
obj3 + obj4

California        NaN
Ohio           7000.0
Oregon         3200.0
Texas         14200.0
Utanh             NaN
dtype: float64

In [43]:
obj3.add(obj4,fill_value = 100)

California        NaN
Ohio           7000.0
Oregon         3200.0
Texas         14200.0
Utanh           600.0
dtype: float64

In [44]:
obj4

state
California       NaN
Ohio          3500.0
Oregon        1600.0
Texas         7100.0
Name: population, dtype: float64

In [45]:
np.mean(obj4.values)

nan

In [46]:
np.mean(obj4)

4066.6666666666665

In [47]:

# DataFrame
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year':[2000,1998,2002,20001,2001,2002],
       'pop':[1.5, 1.7, 3.6, 2.4, 2.9, 3.0]}

In [48]:
frame = pd.DataFrame(data)

In [49]:
frame

state   year  pop
0    Ohio   2000  1.5
1    Ohio   1998  1.7
2    Ohio   2002  3.6
3  Nevada  20001  2.4
4  Nevada   2001  2.9
5  Nevada   2002  3.0

In [50]:
frame.head()

state   year  pop
0    Ohio   2000  1.5
1    Ohio   1998  1.7
2    Ohio   2002  3.6
3  Nevada  20001  2.4
4  Nevada   2001  2.9

In [51]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
            index=['one','two','three', 'four', 'five', 'six'])

In [52]:
frame

state   year  pop
0    Ohio   2000  1.5
1    Ohio   1998  1.7
2    Ohio   2002  3.6
3  Nevada  20001  2.4
4  Nevada   2001  2.9
5  Nevada   2002  3.0

In [53]:


frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [54]:
frame.values

array([['Ohio', 2000, 1.5],
       ['Ohio', 1998, 1.7],
       ['Ohio', 2002, 3.6],
       ['Nevada', 20001, 2.4],
       ['Nevada', 2001, 2.9],
       ['Nevada', 2002, 3.0]], dtype=object)

In [55]:

frame.index

RangeIndex(start=0, stop=6, step=1)

In [56]:
frame.iloc[:,1]

0     2000
1     1998
2     2002
3    20001
4     2001
5     2002
Name: year, dtype: int64

In [57]:
ar1 = np.array(['hello', 'world', 'fuck'])

In [58]:
ar1

array(['hello', 'world', 'fuck'], dtype='<U5')

In [59]:
np.char.multiply(ar1,2)

array(['hellohello', 'worldworld', 'fuckfuck'], dtype='<U10')

In [60]:

ar1 = np.array(['hello', 'world', 'fuck'], dtype=object)

In [61]:
ar1

array(['hello', 'world', 'fuck'], dtype=object)

In [62]:
ar1*2

array(['hellohello', 'worldworld', 'fuckfuck'], dtype=object)

In [63]:
ar1

array(['hello', 'world', 'fuck'], dtype=object)

In [64]:
frame

state   year  pop
0    Ohio   2000  1.5
1    Ohio   1998  1.7
2    Ohio   2002  3.6
3  Nevada  20001  2.4
4  Nevada   2001  2.9
5  Nevada   2002  3.0

In [65]:
state_column = frame['state'] # 利用column名进行索引

In [66]:
state_column

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [67]:
type(state_column)

pandas.core.series.Series

In [68]:
frame.year

0     2000
1     1998
2     2002
3    20001
4     2001
5     2002
Name: year, dtype: int64

In [69]:
state_column

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [70]:
state_column[0]

'Ohio'

In [71]:
state_column.index = np.arange(1,state_column.size+1)

In [72]:
state_column

1      Ohio
2      Ohio
3      Ohio
4    Nevada
5    Nevada
6    Nevada
Name: state, dtype: object

In [73]:
type(frame.loc[1]) # 一行也是一个Series

pandas.core.series.Series

In [74]:
frame

state   year  pop
0    Ohio   2000  1.5
1    Ohio   1998  1.7
2    Ohio   2002  3.6
3  Nevada  20001  2.4
4  Nevada   2001  2.9
5  Nevada   2002  3.0

In [75]:
frame2

year   state  pop debt
one     2000    Ohio  1.5  NaN
two     1998    Ohio  1.7  NaN
three   2002    Ohio  3.6  NaN
four   20001  Nevada  2.4  NaN
five    2001  Nevada  2.9  NaN
six     2002  Nevada  3.0  NaN

In [76]:
frame2['debt'] = 13.2
np.disp(frame2['debt'])

one      13.2
two      13.2
three    13.2
four     13.2
five     13.2
six      13.2
Name: debt, dtype: float64


In [77]:
frame2

year   state  pop  debt
one     2000    Ohio  1.5  13.2
two     1998    Ohio  1.7  13.2
three   2002    Ohio  3.6  13.2
four   20001  Nevada  2.4  13.2
five    2001  Nevada  2.9  13.2
six     2002  Nevada  3.0  13.2

In [78]:
frame2['debt'] = np.arange(6.0)

In [79]:
frame2

year   state  pop  debt
one     2000    Ohio  1.5   0.0
two     1998    Ohio  1.7   1.0
three   2002    Ohio  3.6   2.0
four   20001  Nevada  2.4   3.0
five    2001  Nevada  2.9   4.0
six     2002  Nevada  3.0   5.0

In [80]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [81]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [82]:
frame2['debt'] = val

In [83]:
frame2

year   state  pop  debt
one     2000    Ohio  1.5   NaN
two     1998    Ohio  1.7  -1.2
three   2002    Ohio  3.6   NaN
four   20001  Nevada  2.4  -1.5
five    2001  Nevada  2.9  -1.7
six     2002  Nevada  3.0   NaN

In [84]:
frame2.fillna(1) # 填充缺失值

year   state  pop  debt
one     2000    Ohio  1.5   1.0
two     1998    Ohio  1.7  -1.2
three   2002    Ohio  3.6   1.0
four   20001  Nevada  2.4  -1.5
five    2001  Nevada  2.9  -1.7
six     2002  Nevada  3.0   1.0

In [85]:
frame2['eastern'] = frame2.state == 'Ohio'

In [86]:
frame2

year   state  pop  debt  eastern
one     2000    Ohio  1.5   NaN     True
two     1998    Ohio  1.7  -1.2     True
three   2002    Ohio  3.6   NaN     True
four   20001  Nevada  2.4  -1.5    False
five    2001  Nevada  2.9  -1.7    False
six     2002  Nevada  3.0   NaN    False

In [87]:
del frame2['eastern']

In [88]:
frame2

year   state  pop  debt
one     2000    Ohio  1.5   NaN
two     1998    Ohio  1.7  -1.2
three   2002    Ohio  3.6   NaN
four   20001  Nevada  2.4  -1.5
five    2001  Nevada  2.9  -1.7
six     2002  Nevada  3.0   NaN

In [89]:
frame

state   year  pop
0    Ohio   2000  1.5
1    Ohio   1998  1.7
2    Ohio   2002  3.6
3  Nevada  20001  2.4
4  Nevada   2001  2.9
5  Nevada   2002  3.0

In [90]:
fuck = frame['state'].copy()

In [91]:
fuck

1      Ohio
2      Ohio
3      Ohio
4    Nevada
5    Nevada
6    Nevada
Name: state, dtype: object

In [92]:
fuck[1]

'Ohio'

In [93]:
fuck[1] = 'fuck'

In [94]:
frame

state   year  pop
0    Ohio   2000  1.5
1    Ohio   1998  1.7
2    Ohio   2002  3.6
3  Nevada  20001  2.4
4  Nevada   2001  2.9
5  Nevada   2002  3.0

In [95]:
fuck

1      fuck
2      Ohio
3      Ohio
4    Nevada
5    Nevada
6    Nevada
Name: state, dtype: object

In [96]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [97]:
frame3 = DataFrame(pop)

In [98]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [99]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [100]:
frame2

year   state  pop  debt
one     2000    Ohio  1.5   NaN
two     1998    Ohio  1.7  -1.2
three   2002    Ohio  3.6   NaN
four   20001  Nevada  2.4  -1.5
five    2001  Nevada  2.9  -1.7
six     2002  Nevada  3.0   NaN

In [101]:
frame2.T

one   two three    four    five     six
year   2000  1998  2002   20001    2001    2002
state  Ohio  Ohio  Ohio  Nevada  Nevada  Nevada
pop     1.5   1.7   3.6     2.4     2.9     3.0
debt    NaN  -1.2   NaN    -1.5    -1.7     NaN

In [102]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
            index=['one','two','three', 'four', 'five', 'seven'])

In [103]:
frame2

year   state  pop debt
one     2000    Ohio  1.5  NaN
two     1998    Ohio  1.7  NaN
three   2002    Ohio  3.6  NaN
four   20001  Nevada  2.4  NaN
five    2001  Nevada  2.9  NaN
seven   2002  Nevada  3.0  NaN

In [104]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [105]:
pdata = {'Ohio': frame3['Ohio'],
        'Nevada': frame3['Nevada']}
# 利用series创建dataframe

In [106]:
pdata

{'Ohio': 2001    1.7
 2002    3.6
 2000    1.5
 Name: Ohio, dtype: float64,
 'Nevada': 2001    2.4
 2002    2.9
 2000    NaN
 Name: Nevada, dtype: float64}

In [107]:
df = pd.DataFrame(pdata)

In [108]:
df.index.name = 'time'
df.columns.name = 'area'
df.name = 'dataframe'

In [109]:
df

area  Ohio  Nevada
time              
2001   1.7     2.4
2002   3.6     2.9
2000   1.5     NaN

In [110]:
frame2

year   state  pop debt
one     2000    Ohio  1.5  NaN
two     1998    Ohio  1.7  NaN
three   2002    Ohio  3.6  NaN
four   20001  Nevada  2.4  NaN
five    2001  Nevada  2.9  NaN
seven   2002  Nevada  3.0  NaN

In [111]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [1998, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [20001, 'Nevada', 2.4, nan],
       [2001, 'Nevada', 2.9, nan],
       [2002, 'Nevada', 3.0, nan]], dtype=object)

In [112]:
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [113]:
pd.DataFrame(arr,index=np.arange(1,arr[:,1].size+1), columns=['a', 'b', 'c', 'd', 'e'])  # 使用行的范围设置index

a   b   c   d   e
1   0   1   2   3   4
2   5   6   7   8   9
3  10  11  12  13  14
4  15  16  17  18  19

In [114]:
# 索引对象 index 是不可以改变的 columns是可以改变的
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index

In [115]:
index

Index(['a', 'b', 'c'], dtype='object')

In [116]:
index[1:]

Index(['b', 'c'], dtype='object')

In [117]:
# 索引对象不可以改变
index[0] = 'a'

TypeError: Index does not support mutable operations

In [ ]:
labels = pd.Index(np.arange(3))

In [ ]:
labels

In [ ]:
pd.Index?

In [ ]:
labels = pd.Index(list('abc')) # 相比手动输入 更加快速

In [118]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

NameError: name 'labels' is not defined

In [119]:
obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [120]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [121]:
obj2.index is labels

NameError: name 'labels' is not defined

In [122]:
frame3

Nevada  Ohio
time              
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [123]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object')

In [124]:
'Ohio' in frame3.columns

True

In [125]:
2003 in frame3.index

False

In [126]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [127]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [128]:
ar4 = np.arange(8).reshape(4,2)

In [129]:
ar4

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [130]:
frame5 = pd.DataFrame(ar4, index=dup_labels, columns=['col1', 'col2'])

In [131]:
frame5

col1  col2
foo     0     1
foo     2     3
bar     4     5
bar     6     7

In [132]:
frame5['col1']

foo    0
foo    2
bar    4
bar    6
Name: col1, dtype: int32

In [133]:
frame5.loc['foo']

col1  col2
foo     0     1
foo     2     3

In [134]:
s1 = pd.Series([1,2])
s1

0    1
1    2
dtype: int64

In [135]:
index1 = pd.Index(np.arange(10))

In [136]:
index2 = pd.Index(np.random.randint(1,100,size=(10)))

In [137]:
index2.append(index1) # 追加内容 和list 相似

Int64Index([53, 72, 69, 27, 22, 86, 90, 20, 97, 38, 0, 1, 2, 3, 4, 5, 6, 7, 8,
            9],
           dtype='int64')

In [138]:
index2

Int64Index([53, 72, 69, 27, 22, 86, 90, 20, 97, 38], dtype='int64')

In [139]:
index1.difference(index2) # 差集

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [140]:
index1.isin([1,2,3]) # 判断值是否在其中

array([False,  True,  True,  True, False, False, False, False, False,
       False])

In [141]:
index1.delete(1)

Int64Index([0, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [142]:
index1.insert(1,10)

Int64Index([0, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [143]:
index1

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [144]:
index1.is_unique

True

In [145]:
index1.is_monotonic

True

In [148]:
index1.unique()

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [149]:
# 1 # 海龟绘图
# import turtle     #导入模块或库
# t=turtle.Pen()    # 用t代表模块中Pen这个功能，即表示海龟的钢笔
 
# for x in range(360): #设置360次循环
#     t.forward(x)     # 缩进代码，表示位于循环之中，钢笔向前走x步
#     t.left(59)

 
# colors=['red','yellow','blue','green']  #将颜色存储为列表
 
# for x in range(100):
 
#     t.pencolor(colors[x%4])  # 表示颜色从colors变量中遍历
 
#     t.circle(x)
 
#     t.left(91)

# t=turtle.Pen()
 
# colors=['red','yellow','blue','green','orange','purple']
 
# sides = 6
 
# for x in range(50):
 
#     t.pencolor(colors[x%sides])
 
#     t.forward(x*3/sides+x)
 
#     t.left(360/sides+1)
 
#     t.width(x*sides/200)   # 笔的宽度

In [150]:
# 重建索引
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=pd.Index(list('dbac')))

In [151]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [152]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [153]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [154]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [155]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [156]:
obj3.reindex?

In [157]:
index = ['Firefox', 'Chrome', 'Safari', 'IE10', 'Konqueror']
df = pd.DataFrame({'http_status': [200, 200, 404, 404, 301],
                 'response_time': [0.04, 0.02, 0.07, 0.08, 1.0]},
                 index=index)
new_index = ['Safari', 'Iceweasel', 'Comodo Dragon', 'IE10',
              'Chrome']

In [158]:
df

http_status  response_time
Firefox            200           0.04
Chrome             200           0.02
Safari             404           0.07
IE10               404           0.08
Konqueror          301           1.00

In [159]:
df.reindex(index=new_index)

http_status  response_time
Safari               404.0           0.07
Iceweasel              NaN            NaN
Comodo Dragon          NaN            NaN
IE10                 404.0           0.08
Chrome               200.0           0.02

In [160]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index=['a', 'c', 'd'],
                    columns=['Ohio', 'Texas', 'California'])

In [161]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [162]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [163]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [164]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [165]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [166]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [167]:
obj = pd.Series(np.arange(5.), index=pd.Index(list('abcce')))

In [168]:
obj

a    0.0
b    1.0
c    2.0
c    3.0
e    4.0
dtype: float64

In [169]:
new_obj = obj.drop('c')

In [170]:
obj

a    0.0
b    1.0
c    2.0
c    3.0
e    4.0
dtype: float64

In [171]:
new_obj

a    0.0
b    1.0
e    4.0
dtype: float64

In [172]:
obj.drop(['a', 'c'])

b    1.0
e    4.0
dtype: float64

In [173]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [174]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [175]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [176]:
new_data = data.drop(['one', 'four'], axis=1, inplace=True) # 对列进行操作

In [178]:
new_data

In [179]:
new_data.drop?

Object `new_data.drop` not found.


In [180]:
data # inplce false 对原值产生影响

two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

In [181]:
data.reindex?

In [182]:
del data['two']

In [183]:
data

three
Ohio          2
Colorado      6
Utah         10
New York     14

In [184]:
new_data is None

True

In [185]:
data

three
Ohio          2
Colorado      6
Utah         10
New York     14

In [186]:
data.drop('three',axis='columns')

Empty DataFrame
Columns: []
Index: [Ohio, Colorado, Utah, New York]

In [187]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [188]:
obj['b']

1.0

In [189]:
obj[1]

1.0

In [190]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [191]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [192]:
obj[[1, 2, 3]]

b    1.0
c    2.0
d    3.0
dtype: float64

In [193]:
obj[obj < 3]

a    0.0
b    1.0
c    2.0
dtype: float64

In [194]:
obj['a':'c']

a    0.0
b    1.0
c    2.0
dtype: float64

In [195]:
obj[:2]

a    0.0
b    1.0
dtype: float64

In [196]:
obj['a':'c'] = 10 # 切片作左值

In [197]:
obj

a    10.0
b    10.0
c    10.0
d     3.0
dtype: float64

In [198]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [199]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [200]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [201]:
data[['two', 'three']] = 10

In [202]:
data

one  two  three  four
Ohio        0   10     10     3
Colorado    4   10     10     7
Utah        8   10     10    11
New York   12   10     10    15

In [203]:
data[:2]

one  two  three  four
Ohio        0   10     10     3
Colorado    4   10     10     7

In [204]:
data['three'] > 5 # 是否利用了广播特性

Ohio        True
Colorado    True
Utah        True
New York    True
Name: three, dtype: bool

In [205]:
data[data['three'] > 5] # 指定bool值数组进行选择元素

one  two  three  four
Ohio        0   10     10     3
Colorado    4   10     10     7
Utah        8   10     10    11
New York   12   10     10    15

In [206]:
data < 5

one    two  three   four
Ohio       True  False  False   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [207]:
data[data < 5] = 0

In [208]:
data

one  two  three  four
Ohio        0   10     10     0
Colorado    0   10     10     7
Utah        8   10     10    11
New York   12   10     10    15

In [209]:
data[:2] # 使用切片索引行 

one  two  three  four
Ohio        0   10     10     0
Colorado    0   10     10     7

In [210]:
data.loc['Colorado', ['two', 'three']] # 使用labels标签进行索引

two      10
three    10
Name: Colorado, dtype: int64

In [211]:
data.iloc[2, [3, 0, 1]] # 使用位置进行索引

four    11
one      8
two     10
Name: Utah, dtype: int64

In [212]:
data.iloc[2] # 默认是列取:

one       8
two      10
three    10
four     11
Name: Utah, dtype: int64

In [213]:
data.iloc[[1, 2], [3, 0, 1]] # 取的是对应的组合 和 python中的以xy配对的神奇索引方式不同的索引

four  one  two
Colorado     7    0   10
Utah        11    8   10

In [215]:
data.loc[:'Utah', 'two'] # 对行进行切片 同时选择two列

Ohio        10
Colorado    10
Utah        10
Name: two, dtype: int64

In [223]:
data.loc[:, 'three'] = np.arange(data.loc[:, 'three'].size)
data.iloc[:, :3][data.three > 1]  # 布尔值索引 选择的是为True的行

one  two  three
Utah        8   10      2
New York   12   10      3

In [217]:
data.three > 5

Ohio        True
Colorado    True
Utah        True
New York    True
Name: three, dtype: bool

In [218]:
data.iloc[:, :3]

one  two  three
Ohio        0   10     10
Colorado    0   10     10
Utah        8   10     10
New York   12   10     10

In [224]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [225]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [226]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [227]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [228]:
data [data < 5] 

one  two  three  four
Ohio      0.0  1.0    2.0   3.0
Colorado  4.0  NaN    NaN   NaN
Utah      NaN  NaN    NaN   NaN
New York  NaN  NaN    NaN   NaN

In [229]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [231]:
data.at['Ohio', 'one'] # 只获取单个元素

0

In [232]:
data.iat[1,2]

6

In [238]:
data._get_value('Ohio', 'one')

0

In [239]:
data._get_value?

In [5]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=pd.Index(list('acde')))

In [7]:
s2 = pd.Series([-2.1, -2.5, 3, 3.4, 1.5], index=pd.Index(list('acefg')))

In [8]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [9]:
s2

a   -2.1
c   -2.5
e    3.0
f    3.4
g    1.5
dtype: float64

In [10]:
s1 + s2

a    5.2
c   -5.0
d    NaN
e    4.5
f    NaN
g    NaN
dtype: float64

In [11]:
s1.add(s2, fill_value=10)

a     5.2
c    -5.0
d    13.4
e     4.5
f    13.4
g    11.5
dtype: float64

In [13]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                  index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [14]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [15]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [16]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [18]:
df1.add(df2, fill_value=0) # fill_value 什么意思？

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0