In [236]:
# 因笔记本错误导致不全
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

In [237]:
arr = np.arange(12.).reshape((3, 4))

In [238]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [239]:
arr[0] # 访问的一行

array([0., 1., 2., 3.])

In [240]:
arr - arr[0] # numpy数组的广播机制 broadcast

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [241]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [242]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [243]:
frame['b'] # 选择一列

Utah      0.0
Ohio      3.0
Texas     6.0
Oregon    9.0
Name: b, dtype: float64

In [244]:
series = frame.loc['Utah']

In [245]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [246]:
frame - series # 广播机制 默认是匹配列然后向下广播行 如果不存在则置为NaN

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [247]:
frame - frame['b'] # 由于匹配均不存在 因此错误

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [248]:
series3 = frame['d']

In [249]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [250]:
frame.sub(series3, axis='index').fillna(10) # 和行匹配 以列的方向广播

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [251]:
# numpy 中的逐元素数组方法对pandas适用
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [252]:
frame

b         d         e
Utah    1.479273 -0.304695  0.495263
Ohio    0.291459 -1.360466 -1.292151
Texas  -1.157606  0.291481  0.826076
Oregon  1.152661  0.464555  0.288971

In [253]:
np.abs(frame) # 逐元素取绝对值

b         d         e
Utah    1.479273  0.304695  0.495263
Ohio    0.291459  1.360466  1.292151
Texas   1.157606  0.291481  0.826076
Oregon  1.152661  0.464555  0.288971

In [254]:
np.square(frame)

b         d         e
Utah    2.188249  0.092839  0.245286
Ohio    0.084948  1.850866  1.669653
Texas   1.340051  0.084961  0.682401
Oregon  1.328628  0.215811  0.083504

In [255]:
DataFrame.apply?

In [256]:
DataFrame.sub?

In [257]:
f = lambda x: x.max() - x.min()
f2 = lambda x: "%.2f" %x

In [258]:
frame

b         d         e
Utah    1.479273 -0.304695  0.495263
Ohio    0.291459 -1.360466 -1.292151
Texas  -1.157606  0.291481  0.826076
Oregon  1.152661  0.464555  0.288971

In [259]:
frame.apply(f, axis='columns', raw=True)

Utah      1.783968
Ohio      1.651925
Texas     1.983681
Oregon    0.863690
dtype: float64

In [260]:
series = Series([1,2,3])

In [261]:
series

0    1
1    2
2    3
dtype: int64

In [262]:
series.map(f2) # 设置格式 

0    1.00
1    2.00
2    3.00
dtype: object

In [263]:
# 自定义函数处理批量元素
#1.python内置的map函数

lst = [1,2,3]
f = lambda x: x * 10
lst2 = list(map(f, lst))
np.disp(lst2) # 显示元素
print('________________')


#2.Series中的map函数
# 和python中的map相似 只不过输入Series的一个方法

series = Series([1,2,3])
f2 = lambda x: "%.2f" %x
np.disp(series.map(f2)) # 设置格式 
print('________________')

#3.Series中的apply函数
# 自由度更高的一种
np.disp(series.apply(f2))

#4.DataFrame中的apply函数
"""
func:传入的函数，多为自定义的lambda函数
axis:可以指定对行或者列的操作 默认为沿着行的方向(axis='index'/0)
raw:以Series的方式传入False(default)还是转换成ndarray(True)再传入
"""
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame.apply(lambda x: min(x), axis='index', raw=True) # 计算每列的最小值
# 其返回值不一定是一个标量 也可以生成一个dataframe 但要构建新的Series
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f, axis=0) # 对每一个列都返回一个Series 索引为行

#5.DataFrame中的applymap函
"""
为了和Series中的map区别开 applymap是元素级函数 操作frame中的每个元素
在函数定义时 就不再是apply那样以一个Series传入了 而是一个single value
在定义函数时要注意不要使用sum、min等这样只针对Series适用的函数
"""
frame.applymap(lambda x: '%.2f' %x) # 逐元素操作

[10, 20, 30]
________________
0    1.00
1    2.00
2    3.00
dtype: object
________________
0    1.00
1    2.00
2    3.00
dtype: object


b      d      e
Utah    0.00   1.00   2.00
Ohio    3.00   4.00   5.00
Texas   6.00   7.00   8.00
Oregon  9.00  10.00  11.00

In [264]:
# 排名和排序
obj = pd.Series(range(4), index=list('dabc'))

In [265]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [266]:
obj.sort_index

<bound method Series.sort_index of d    0
a    1
b    2
c    3
dtype: int64>

In [267]:
obj.sort_values

<bound method Series.sort_values of d    0
a    1
b    2
c    3
dtype: int64>

In [268]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [269]:
frame1 = frame.reindex(columns=['b', 'e', 'd'])
frame1 = frame1.sort_index(axis=1) # 按照列的标签进行排序
frame1 ==  frame

b     d     e
Utah    True  True  True
Ohio    True  True  True
Texas   True  True  True
Oregon  True  True  True

In [270]:
frame.sort_index(ascending=False) # 按照行的标签进行排序

b     d     e
Utah    0.0   1.0   2.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
Ohio    3.0   4.0   5.0

In [271]:
frame.sort_values(by='d', kind='stable')

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [272]:
obj = Series([7,-5, 7, 4, 2, 0, 4])

In [273]:
index1 = obj.rank().sort_values().index # 对数据进行排名
obj1 = obj.reindex(index1)

In [274]:
obj1

1   -5
5    0
4    2
3    4
6    4
0    7
2    7
dtype: int64

In [275]:
obj.rank(method='average')

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [276]:
obj.rank(method='max', ascending=False)

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [277]:
frame = DataFrame({'b':[4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                  'c': [-2, 5, 8, -2.5]})

In [278]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [279]:
frame.rank(method='first') # 默认是行排名

b    a    c
0  3.0  1.0  2.0
1  4.0  3.0  3.0
2  1.0  2.0  4.0
3  2.0  4.0  1.0

In [280]:
frame.rank(axis=1, method='first', ascending=False) # 对列进行逆序排列 使用max

b    a    c
0  1.0  2.0  3.0
1  1.0  3.0  2.0
2  3.0  2.0  1.0
3  1.0  2.0  3.0

In [281]:
obj = Series(range(5), index=list('aabbc'))

In [282]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [283]:
obj['a']

a    0
a    1
dtype: int64

In [284]:
del obj['a']

In [285]:
obj

b    2
b    3
c    4
dtype: int64

In [286]:
obj.drop('c')

b    2
b    3
dtype: int64

In [287]:
obj.index.is_unique

False

In [288]:
obj.is_unique?

In [289]:
obj['d'] = 2

In [290]:
obj.is_unique

False

In [291]:
df = DataFrame(np.random.randn(4, 3), index=list('aabb'))

In [292]:
df.index.is_unique

False

In [293]:
df.columns.is_unique

True

In [294]:
df.loc['b']

0         1         2
b -0.046444  1.201641  1.428921
b -0.823463 -2.603635  0.758287

In [295]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                  [np.nan, np.nan], [0.75, -1.3]],
                 index=list('abcd'),
                 columns=['one', 'two'])

In [296]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [297]:
df.sum() # 列求和 沿着行方向

one    9.25
two   -5.80
dtype: float64

In [298]:
df - df.loc['b']

one  two
a -5.70  NaN
b  0.00  0.0
c   NaN  NaN
d -6.35  3.2

In [299]:
df.sum(axis=1) # 沿着列的方向 对行求和

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [300]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [301]:
df.idxmax() # 同样是列

one    b
two    d
dtype: object

In [302]:
type(df.idxmax()) # Series

pandas.core.series.Series

In [303]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [304]:
obj = pd.Series(list('aabc'*4))

In [305]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [306]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [307]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [308]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [309]:
df['three'] = list('fuck')

In [310]:
df

one  two three
a  1.40  NaN     f
b  7.10 -4.5     u
c   NaN  NaN     c
d  0.75 -1.3     k

In [311]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [312]:
df # 为什么被省略

one  two three
a  1.40  NaN     f
b  7.10 -4.5     u
c   NaN  NaN     c
d  0.75 -1.3     k

In [313]:
df.iloc[0, [0, 1]] = 'f'

In [314]:
df

one  two three
a     f    f     f
b   7.1 -4.5     u
c   NaN  NaN     c
d  0.75 -1.3     k

In [315]:
df.describe()

one two three
count    3   3     4
unique   3   3     4
top      f   f     f
freq     1   1     1

In [316]:
df.describe?

In [317]:
df

one  two three
a     f    f     f
b   7.1 -4.5     u
c   NaN  NaN     c
d  0.75 -1.3     k

In [318]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                  [np.nan, np.nan], [0.75, -1.3]],
                 index=list('abcd'),
                 columns=['one', 'two'])

In [319]:
df['two'].argmin()

1

In [320]:
df.idxmin()

one    d
two    b
dtype: object

In [321]:
df.quantile()

one    1.4
two   -2.9
Name: 0.5, dtype: float64

In [322]:
df.var()

one    12.205833
two     5.120000
dtype: float64

In [323]:
df.std()

one    3.493685
two    2.262742
dtype: float64

In [324]:
df.skew()

one    1.664846
two         NaN
dtype: float64

In [325]:
df.kurt()

one   NaN
two   NaN
dtype: float64

In [326]:
df.cumprod()

one   two
a  1.400   NaN
b  9.940 -4.50
c    NaN   NaN
d  7.455  5.85

In [327]:
df.diff()

one  two
a  NaN  NaN
b  5.7  NaN
c  NaN  NaN
d  NaN  NaN

In [328]:
df.pct_change()

one       two
a       NaN       NaN
b  4.071429       NaN
c  0.000000  0.000000
d -0.894366 -0.711111

In [340]:
file_name = r'C:\Users\zhaolei\Downloads\GE.csv'

In [341]:
df = pd.read_csv(file_name)

In [342]:
df

Date       Open       High        Low      Close  Adj Close   Volume
0   2019-09-09  70.000000  72.400002  69.839996  71.680000  70.888985  6245063
1   2019-09-10  71.279999  74.160004  71.199997  73.120003  72.313110  7827150
2   2019-09-11  73.199997  74.879997  72.480003  74.879997  74.053658  7136863
3   2019-09-12  75.199997  76.160004  73.760002  74.080002  73.262489  8514388
4   2019-09-13  74.480003  75.599998  73.120003  74.720001  73.975311  5698675
5   2019-09-16  74.400002  75.360001  73.360001  75.040001  74.292137  5718550
6   2019-09-17  74.400002  75.120003  74.000000  74.879997  74.133713  4744250
7   2019-09-18  74.480003  75.120003  73.440002  75.040001  74.292137  5033838
8   2019-09-19  74.800003  76.000000  74.720001  75.360001  74.608940  4241913
9   2019-09-20  75.680000  76.320000  74.720001  74.959999  74.212921  7191300
10  2019-09-23  73.760002  75.120003  73.599998  74.720001  73.975311  4188888
11  2019-09-24  74.480003  74.800003  71.680000  71.760002  71.044815  6667875
12  2019-09-25  71.680000  73.599998  71.519997  73.279999  72.549660  5482425
13  2019-09-26  73.440002  73.680000  71.680000  72.160004  71.440842  4653725
14  2019-09-27  72.320000  73.360001  71.919998  72.320000  71.599236  3813875
15  2019-09-30  72.639999  72.800003  71.519997  71.519997  70.807205  4386425
16  2019-10-01  71.680000  72.320000  68.080002  68.879997  68.193520  8597325
17  2019-10-02  68.480003  68.959999  67.279999  68.080002  67.401497  5940100
18  2019-10-03  68.000000  69.680000  66.000000  69.680000  68.985550  7328325
19  2019-10-04  68.879997  69.599998  68.320000  68.559998  67.876724  6534100
20  2019-10-07  68.400002  69.199997  67.839996  68.480003  67.797523  4021300
21  2019-10-08  67.839996  68.000000  66.160004  66.239998  65.579826  5687800
22  2019-10-09  66.480003  66.959999  65.919998  66.800003  66.134254  4105100

In [343]:
df.corr() # 相关性

Open      High       Low     Close  Adj Close    Volume
Open       1.000000  0.969009  0.951794  0.893148   0.894461  0.071983
High       0.969009  1.000000  0.958108  0.952063   0.951888  0.141766
Low        0.951794  0.958108  1.000000  0.953376   0.954138 -0.078152
Close      0.893148  0.952063  0.953376  1.000000   0.999949 -0.001619
Adj Close  0.894461  0.951888  0.954138  0.999949   1.000000 -0.007046
Volume     0.071983  0.141766 -0.078152 -0.001619  -0.007046  1.000000

In [344]:
df.cov() # 协方差

Open           High            Low        Close  \
Open            7.831857       7.769313       7.759422     7.395201   
High            7.769313       8.208144       7.996336     8.070162   
Low             7.759422       7.996336       8.486099     8.216981   
Close           7.395201       8.070162       8.216981     8.753631   
Adj Close       7.315128       7.969600       8.122568     8.645699   
Volume     294486.605093  593738.672739 -332807.684825 -7002.584120   

              Adj Close        Volume  
Open           7.315128  2.944866e+05  
High           7.969600  5.937387e+05  
Low            8.122568 -3.328077e+05  
Close          8.645699 -7.002584e+03  
Adj Close      8.539975 -3.009956e+04  
Volume    -30099.556916  2.136988e+12

In [345]:
df.corr()

Open      High       Low     Close  Adj Close    Volume
Open       1.000000  0.969009  0.951794  0.893148   0.894461  0.071983
High       0.969009  1.000000  0.958108  0.952063   0.951888  0.141766
Low        0.951794  0.958108  1.000000  0.953376   0.954138 -0.078152
Close      0.893148  0.952063  0.953376  1.000000   0.999949 -0.001619
Adj Close  0.894461  0.951888  0.954138  0.999949   1.000000 -0.007046
Volume     0.071983  0.141766 -0.078152 -0.001619  -0.007046  1.000000

In [346]:
df['Open'].corr(df['High'])

0.9690088081868775

In [348]:
df.Low.cov(df.Close)

8.216981194939311

In [349]:
df.corrwith?

In [350]:
df.corrwith(df.Open) # 列计算 沿着行

Open         1.000000
High         0.969009
Low          0.951794
Close        0.893148
Adj Close    0.894461
Volume       0.071983
dtype: float64

In [352]:
df.tail()

Date       Open       High        Low      Close  Adj Close   Volume
18  2019-10-03  68.000000  69.680000  66.000000  69.680000  68.985550  7328325
19  2019-10-04  68.879997  69.599998  68.320000  68.559998  67.876724  6534100
20  2019-10-07  68.400002  69.199997  67.839996  68.480003  67.797523  4021300
21  2019-10-08  67.839996  68.000000  66.160004  66.239998  65.579826  5687800
22  2019-10-09  66.480003  66.959999  65.919998  66.800003  66.134254  4105100

In [354]:
df.corrwith(df) # 计算匹配到列名的相关性

Open         1.0
High         1.0
Low          1.0
Close        1.0
Adj Close    1.0
Volume       1.0
dtype: float64

In [355]:
row = df.loc[18]

In [356]:
row

Date         2019-10-03
Open               68.0
High              69.68
Low                66.0
Close             69.68
Adj Close      68.98555
Volume          7328325
Name: 18, dtype: object

In [359]:
df = df.drop('Date', axis=1)

In [360]:
df

Open       High        Low      Close  Adj Close   Volume
0   70.000000  72.400002  69.839996  71.680000  70.888985  6245063
1   71.279999  74.160004  71.199997  73.120003  72.313110  7827150
2   73.199997  74.879997  72.480003  74.879997  74.053658  7136863
3   75.199997  76.160004  73.760002  74.080002  73.262489  8514388
4   74.480003  75.599998  73.120003  74.720001  73.975311  5698675
5   74.400002  75.360001  73.360001  75.040001  74.292137  5718550
6   74.400002  75.120003  74.000000  74.879997  74.133713  4744250
7   74.480003  75.120003  73.440002  75.040001  74.292137  5033838
8   74.800003  76.000000  74.720001  75.360001  74.608940  4241913
9   75.680000  76.320000  74.720001  74.959999  74.212921  7191300
10  73.760002  75.120003  73.599998  74.720001  73.975311  4188888
11  74.480003  74.800003  71.680000  71.760002  71.044815  6667875
12  71.680000  73.599998  71.519997  73.279999  72.549660  5482425
13  73.440002  73.680000  71.680000  72.160004  71.440842  4653725
14  72.320000  73.360001  71.919998  72.320000  71.599236  3813875
15  72.639999  72.800003  71.519997  71.519997  70.807205  4386425
16  71.680000  72.320000  68.080002  68.879997  68.193520  8597325
17  68.480003  68.959999  67.279999  68.080002  67.401497  5940100
18  68.000000  69.680000  66.000000  69.680000  68.985550  7328325
19  68.879997  69.599998  68.320000  68.559998  67.876724  6534100
20  68.400002  69.199997  67.839996  68.480003  67.797523  4021300
21  67.839996  68.000000  66.160004  66.239998  65.579826  5687800
22  66.480003  66.959999  65.919998  66.800003  66.134254  4105100

In [362]:
price = df.pct_change()

In [363]:
df.corrwith(price)

Open         0.422966
High         0.483015
Low          0.376328
Close        0.389525
Adj Close    0.389337
Volume       0.683859
dtype: float64

In [364]:
obj = pd.Series(list('cadaabbcc'))

In [365]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [366]:
uniques = obj.unique()

In [367]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [370]:
obj.value_counts() # 按照数量降序排列

c    3
a    3
b    2
d    1
dtype: int64

In [371]:
pd.value_counts(obj.values, sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [372]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [373]:
mask = obj.isin(['b', 'c'])

In [374]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [375]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [382]:
obj.mask(~mask, 10)

0     c
1    10
2    10
3    10
4    10
5     b
6     b
7     c
8     c
dtype: object

In [383]:
to_match = pd.Series(list('cabbca'))

In [384]:
to_match

0    c
1    a
2    b
3    b
4    c
5    a
dtype: object

In [385]:
unique_vals = pd.Series(list('cba'))

In [386]:
unique_vals

0    c
1    b
2    a
dtype: object

In [387]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [388]:
data = DataFrame({'Qu1': [1, 2, 3, 4],
                 'Qu2': [2, 3, 1, 2]})

In [389]:
data

Qu1  Qu2
0    1    2
1    2    3
2    3    1
3    4    2

In [393]:
data.apply(pd.value_counts).fillna(0) # 传入函数名

Qu1  Qu2
1    1  1.0
2    1  2.0
3    1  1.0
4    1  0.0